# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-09 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200109_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_logged_in',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
