# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-13 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200113_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='reseller',
            field=models.BooleanField(default=False),
        ),
    ]
