# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-07 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('offer', models.CharField(choices=[(1, '5'), (2, '10'), (3, '25'), (4, '50'), (5, '75')], default='', max_length=2)),
                ('category', models.CharField(choices=[(1, 'Electronic & Computers'), (2, 'Movies, TV, Music & Games'), (3, 'Toys, Children & Baby'), (4, 'Clothes, Shoes & Whatces'), (5, 'Health & Beauty')], default='', max_length=2)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
