# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-20 20:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25)),
                ('description', models.TextField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('offer', models.DecimalField(choices=[(0, 0), (5, 5), (10, 10), (25, 25), (50, 50), (75, 75)], decimal_places=2, default=0, max_digits=8)),
                ('category', models.CharField(choices=[('Electronic & Computers', 'Electronic & Computers'), ('Movies, TV, Music & Games', 'Movies, TV, Music & Games'), ('Toys, Children & Baby', 'Toys, Children & Baby'), ('Clothes, Shoes & Whatces', 'Clothes, Shoes & Whatces'), ('Health & Beauty', 'Health & Beauty')], default=None, max_length=100)),
                ('discount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=9)),
                ('stock', models.DecimalField(decimal_places=0, default=0, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('vendor', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
