# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-07 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200107_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('1', 'Electronic & Computers'), ('2', 'Movies, TV, Music & Games'), ('3', 'Toys, Children & Baby'), ('4', 'Clothes, Shoes & Whatces'), ('5', 'Health & Beauty')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.CharField(choices=[('1', '0'), ('2', '5'), ('3', '10'), ('4', '25'), ('5', '50'), ('6', '75')], default='1', max_length=2),
        ),
    ]
