# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-07 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200107_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.CharField(choices=[('0', 0), ('5', 5), ('10', 10), ('25', 25), ('50', 50), ('75', 75)], default='0', max_length=2),
        ),
    ]
