# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-07 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200107_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronic & Computers', 'Electronic & Computers'), ('Movies, TV, Music & Games', 'Movies, TV, Music & Games'), ('Toys, Children & Baby', 'Toys, Children & Baby'), ('Clothes, Shoes & Whatces', 'Clothes, Shoes & Whatces'), ('Health & Beauty', 'Health & Beauty')], default=None, max_length=100),
        ),
    ]
