# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-08 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.DecimalField(choices=[(0, '0'), (5, '5%'), (10, '10%'), (25, '25%'), (50, '50%'), (75, '75%')], decimal_places=2, default=0, max_digits=6),
        ),
    ]
