# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-08 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200108_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/static/image/default', null=True, upload_to='images'),
        ),
    ]
