# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-09 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200108_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=9),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.DecimalField(choices=[(0, '0'), (5, '5%'), (10, '10%'), (25, '25%'), (50, '50%'), (75, '75%')], decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
