# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-09 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20200109_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.DecimalField(choices=[(0, '0'), (5, '5%'), (10, '10%'), (25, '25%'), (50, '50%'), (75, '75%')], decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
