# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-12 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='background',
            field=models.CharField(default='default', editable=False, max_length=100),
        ),
    ]
