# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-12 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20200112_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='background',
        ),
    ]
